name = "Gensou"
author = "Maboroshi"
version = "1.21.11-2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b3913421c706bc8b9fb2c27ea3602d8372db13b1e0d7b5443e403558e11149b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
